version: '3.4'
services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql-socket:/run/mysqld/

  slodd:
    build:
      context: .
    depends_on:
      - mysql
    volumes:
      - type: bind
        source: .
        target: /app
      - mysql-socket:/run/mysqld/
    command: rake

volumes:
  mysql-socket:
